log:
  level: debug
  disable_sentry: true

## PostgreSQL connection
db:
  url: postgres://signer:signer@signer-db/signer?sslmode=disable

## Port to listen for incoming GRPC requests
listener:
  addr: :8111

## Port to listen for incoming HTTP requests
rest_gateway:
  addr: :8222


## Available chains configuration
chains:
  list:
      ## Chain ID
    - id: "80002"
      ## RPC endpoint
      rpc: "your_rpc_endpoint_here"
      ## Bridge contract address
      bridge_address: "0x9c9b83Ed9dd4cF8A385b6e318Fb97Cdfc320b627"
      ## Number of confirmations required for the deposit to be considered final
      confirmations: 1

## RabbitMQ configuration
rabbitmq:
  ## RabbitMQ connection URL
  url: amqp://guest:guest@localhost:5672/
  ## Number of instances per each consumer
  consumer_instances: 2
  ## Delivery resend parameters
  resend_params:
    ## Maximum number of retries
    max_retry_count: 5
    ## delivery resend delays
    delays: [1000, 2000, 5000, 10000, 20000, 60000]


## Service signer private key
signer:
  eth_signer: "signer_private_key_here"
