services:
  db:
    image: tokend/postgres-ubuntu:9.6
    hostname: tss-db
    container_name: tss-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=tss
      - POSTGRES_PASSWORD=tss
      - POSTGRES_DB=tss
      - PGDATA=/pgdata
    volumes:
      - tss-data:/pgdata
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U tss" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - 20000:5432

volumes:
  tss-data: