name: Build Bridgeless Signer docker image
on:
  workflow_dispatch:

env:
  CI_ACCESS_TOKEN: ${{ secrets.CI_ACCESS_TOKEN }}

jobs:
  converge-github:
    name: Skaffold Build To Github
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Cache layers
        uses: actions/cache@v3
        with:
          path: "${{ github.workspace }}/.skaffold/cache"
          key: skaffold-${{ hashFiles('**/cache') }}
          restore-keys: |
            skaffold-

      - name: Run Skaffold pipeline as command
        uses: hiberbee/github-action-skaffold@latest
        id: build
        with:
          command: build --tag ${{ github.sha }}
          repository: ghcr.io/${{ github.repository_owner }}