name: Build Bridgeless Signer docker image tag
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+'

env:
  CI_ACCESS_TOKEN: ${{ secrets.CI_ACCESS_TOKEN }}

jobs:
  converge-github:
    name: Skaffold Build To Github
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Cache layers
        uses: actions/cache@v3
        with:
          path: "${{ github.workspace }}/.skaffold/cache"
          key: skaffold-${{ hashFiles('**/cache') }}
          restore-keys: |
            skaffold-

      - name: Run Skaffold pipeline as command
        uses: hiberbee/github-action-skaffold@latest
        id: build
        with:
          command: build --tag ${{ github.ref_name }}
          repository: ghcr.io/${{ github.repository_owner }}

      - uses: shrink/actions-docker-extract@v3
        id: extract
        with:
          image: ghcr.io/$GITHUB_REPOSITORY:$GITHUB_REF_NAME
          path: "/usr/local/bin/bridgeless-signer"

      - uses: ncipollo/release-action@v1
        id: create-release
        with:
          allowUpdates: true
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ${{steps.extract.outputs.destination}}/bridgeless-signer
          asset_name: bridgeless-signer-alpine-linux-amd64
          asset_content_type: application/octet-stream